defaultPortal: myhomeqb
portals:
  - name: metal
    portalId: 7887915
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CL2y_8XPMRIRAA0AQAAA4G0DQAJYAmEAAMgYq7jhAyDB3poaKO7pDDIUPYJorZ6TWdZRnb9FykK5XCts7aM6OAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGBQBgBEAGBA_BgGABAsAwAAAAAAPAIDQhSl5mG-NxnfCd2yxJ4MQZf3qJpYh0oDbmExUgBaAA
        expiresAt: '2024-01-11T13:39:31.798Z'
    personalAccessKey: >-
      CiRiMjQ4OWVkNy00M2Q0LTQxMjktYTc3Yi1hMmE1M2MwMGMxNjAQq7jhAxjB3poaKhkABeaRgtFIcTPPWHDnW5mDBm_vOA6r71iaSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
  - name: gmcc
    portalId: 40232251
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJ2nmsbPMRIRAA0AQAAA4G0DQAJYAmEAAMAYu8qXEyDB3poaKO7pDDIUAB4qalFKiyO6JqiAsqjdYHZ8HN06OAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGBQBgBEAGBA_BgGABAsAwAAAAAAMAIDQhTniEgnfohjsT8cvdu97ArINwNfFEoDbmExUgBaAA
        expiresAt: '2024-01-11T13:46:52.722Z'
    personalAccessKey: >-
      CiQ3NGJjMWU0ZS0yZWI1LTQ5MWUtYWM4My0xMzBmMTY2YzFkNGUQu8qXExjB3poaKhkABeaRgrU3DXADcWWbAmxj13zDR1V5C7eGSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
  - name: myhomeqb
    portalId: 40959747
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPyK9_PPMRIRAA0AQAAA4G0DQAJYAmEAAMgYg_7DEyDB3poaKO7pDDIUHfiwFg9MfhbFLcanIjP7agHumJA6OAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGBQBgBEAGBA_BgGABAsAwAAAAAAPAIDQhTT_XXvSuOg41cD8gccHEU3qdC6d0oDbmExUgBaAA
        expiresAt: '2024-01-12T16:25:04.657Z'
    personalAccessKey: >-
      CiRkMzUxNDUyYy03ZDhkLTQ1YWEtOGYzYy1hNjk0M2E3OTBiY2MQg_7DExjB3poaKhkABeaRgot5vWppxcZjHJEdYci1b4TId7cfSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
